### ISSUE TITLE
User Profile Pictures Issue

### ISSUE THREAD

**Issue by llyrdavies** [WemXPro/tracker#292]
### Product

WemX

### Describe the issue

User uploaded profile pictures appear weirdly in the admin area.

### Product Version

1.9.0

### Pterodactyl Panel Version

1.11.5

**Comment by VanillaChan6571** [comment]
Correct, I dont know why but the pfp image for wemx needs a recode anyways.

**Comment by GIGABAIT93** [comment]
Can you show screenshots of what is wrong with the image

**Comment by VanillaChan6571** [comment]
> Can you show screenshots of what is wrong with the image

![Screenshot 2024-03-05 070457](https://github.com/WemXPro/tracker/assets/39040261/2a9e56f2-2e46-4625-a06a-7dbcab642dec)
![Screenshot 2024-03-05 070403](https://github.com/WemXPro/tracker/assets/39040261/928dbfe2-0649-44b9-96b4-42e45073c3cf)
![Screenshot 2024-03-05 070307](https://github.com/WemXPro/tracker/assets/39040261/81f1c200-c715-48ae-a55d-39c9a3989213)

These images should stick/keep the CIRCLE and should not stretch into OVAL shape.

The OVAL is there due to incorrect shape size or weird image resolution and WemX does not resize/adjust the image like some other sites.

Example would do what discord does is adjust and crop.

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
