### ISSUE TITLE
Allow IP bans back

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#414]
### Describe the issue

I can’t ban IP

### Product Version

2.0.1

**Comment by PadowYT2** [comment]
Not a bug, that's intentional

**Comment by Mubeen142** [comment]
IP bans were disabled intentionally since most users were using the CloudFlare proxy.

The problem that arised was that when an admin banned a cloudflare public ip all other users with that same ip would be banned too.

To remove the restriction of ip banning, you can app/Http/Controllers/Admin/UsersController.php

and remove line 215 to 217

**Comment by Mubeen142** [comment]
IP bans were re-enabled in the next update
